### ISSUE TITLE
Widget Failed to Load

### ISSUE THREAD

**Issue by mattritchie** [rstedman/tfs-pullrequest-dashboard#47]
![image](https://user-images.githubusercontent.com/188066/61599665-7886f000-ac6e-11e9-955f-677b780ee499.png)

Hi,

I'm new to Azure DevOps and I've just installed this into my organisation  getting the following errors.

![image](https://user-images.githubusercontent.com/188066/61599685-9ce2cc80-ac6e-11e9-8e17-df0d77a7d9bd.png)

Have i done something wrong?
I didn't have the option to configure anything, so i'm not sure what to do? Is there any debugging logs anywhere?

**Comment by mattritchie** [comment]
Just looking around in other issues, noticed problems only affecting chrome. Loaded in IE and it has loaded successfully

**Comment by furkick** [comment]
Having the same issue on Chrome: Version 75.0.3770.142 (Official Build) (64-bit)

I can also confirm that IE 1: Version 11.885.17134.0 is working as intended.

**Comment by MikeWilliams-UK** [comment]
It's happening to me as well [Chrome Version 75.0.3770.142 (Official Build) (64-bit)]

**Comment by rstedman** [comment]
this has been fixed in version 2.3.1

**Comment by markshiffer** [comment]
> this has been fixed in version 2.3.1

Using version 2.3.1 on TFS on-prem and Chrome browser I am still seeing this issue. It will load once, but then all subsequent loads by any other user result in a failure to load. If there is any additional info or diagnostics I can provide for you, I  would be happy to do so.

**Comment by rstedman** [comment]
What version of TFS on prem do you have? I only have access to a 2018.2 on-prem instance, which will make troubleshooting difficult if you are on a different version. I am not seeing the same issue on 2018.02.

When you have the dashboard widget open, could you open chrome developer tools and find `appConfig.service.ts`, and look for the following block of code:
![image](https://user-images.githubusercontent.com/5440997/61918655-2240d800-af20-11e9-9b68-72adf55ed669.png)

Does the code look the same for you? If not, try ctrl+f5 to force a cache refresh (TFS set a cache-control header of 1 year when fetching *.js files for extensions, which can cause you not to get updates unless you force a cache refresh).

If the code does look the same, are you able to set a breakpoint on the `if (pageContext.navigation.routeId) {` line, and let me know what the values of `pageContext.navigation.routeId` and `pageContext.hubsContext.selectedHubId` are.

**Comment by markshiffer** [comment]
I have on-prem 2018.2 as well: Version 16.131.27701.1, using Chrome.
I must not be looking in the correct place. I am not able to find appConfig.service.ts in the code. What screen are you on when you are using CDT? I tried from a custom dashboard with the widget on it, again with the widget config open and then from the Pull Request Dashboard under the Code tab.

**Comment by markshiffer** [comment]
I do see the following error in CDT when the widget is not working. I did not notice this when it was working though:

﻿
Content?bundle=vss-b…ZnasnpanuPQzGJ0=:15 Mixed Content: The page at 'https://tfs.[...].com/tfs/DefaultCollection/Marketing/_apps/hub/ryanstedman.tfs-pullrequest-dashboard.tfs-pullrequest-dashboard' was loaded over HTTPS, but requested an insecure resource 'http://tfsapplicationserver:8080/tfs/_apis/public/gallery/publisher/ryanstedman/extension/tfs-pullrequest-dashboard/2.3.1/assetbyname/index.html'. This request has been blocked; the content must be served over HTTPS.

**Comment by rstedman** [comment]
This seems like a server configuration issue. It looks like your tfs server is configured to use SSL but for some reason it's serving extensions over http, which the browser will refuse to load. This is not something I have any control over - maybe your server admin can look into it?
